name: Snyk-ArmorCode GitHub Action
on:
  push:
    branches: 
      - master 
env:
  armorCode_projectName: 'demo-project-aws'
  armorCode_MicroserviceName: 'demo-microservice-aws'
  
jobs:
  Snyk-Scan:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Snyk-Scan
        run: py /home/ec2-user/scripts/import_scan.py --githubProjectName ${{ github.repository }} --githubOrg ${{ github.repository_owner }}  --armorcodeProductName ${{env.armorCode_projectName}} --armorcodeSubProductName ${{env.armorCode_MicroserviceName}}
